const calendar = document.getElementById("calendar")
const data1 = document.getElementById("data1")
const data2 = document.getElementById("data2")
const enviar = document.getElementById("enviar")
const itens = document.querySelectorAll("td")